# Generated by Django 5.2.8 on 2025-12-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamos',
            options={'permissions': (('Ver_prestamos', 'Puede ves prstamos'), ('Gestionar_prestamos', 'Puede gestionar préstamos'))},
        ),
    ]
