# Generated by Django 5.2.8 on 2025-12-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_libro_descripcion_libro_isbn_alter_libro_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamos',
            options={'permissions': (('Ver_prestamos', 'Puede ver préstamos'), ('Gestionar_prestamos', 'Puede gestionar préstamos'))},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='image',
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='ejemplares_disponibles',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('p', 'Prestado'), ('m', 'Multa'), ('d', 'Devuelto')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='multa_fija',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='tipo_multa',
            field=models.CharField(choices=[('retraso', 'Retraso'), ('perdida', 'Pérdida'), ('danio', 'Daño'), ('robo', 'Robo'), ('otros', 'Otros')], default='retraso', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_max',
            field=models.DateField(blank=True, null=True),
        ),
    ]
