# Generated by Django 5.2.8 on 2026-01-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_alter_prestamos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='ejemplares_disponibles',
            field=models.IntegerField(default=1),
        ),
    ]
