# Generated by Django 5.2.8 on 2026-01-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_alter_libro_ejemplares_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='tipo_multa',
            field=models.CharField(choices=[('retraso', 'Retraso'), ('perdida', 'Pérdida'), ('danio', 'Daño')], default='retraso', max_length=10),
        ),
    ]
