# Generated by Django 5.2.8 on 2026-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_alter_multa_monto_alter_prestamos_tipo_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='tipo_multa',
            field=models.CharField(choices=[('retraso', 'Retraso'), ('perdida', 'Pérdida'), ('danio', 'Daño'), ('robo', 'Robo'), ('otros', 'Otros')], default='retraso', max_length=10),
        ),
    ]
