# Generated by Django 5.2.8 on 2026-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_alter_prestamos_tipo_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='url_portada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
