# Generated by Django 5.2.8 on 2026-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_libro_url_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='url_portada',
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
