# Generated by Django 5.2.8 on 2026-01-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0012_remove_libro_url_portada_libro_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='portada',
        ),
    ]
