# Generated by Django 5.2.8 on 2026-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0014_libro_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamos',
            options={},
        ),
    ]
