# Generated by Django 5.2.8 on 2026-01-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0015_alter_prestamos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='tipo_multa',
        ),
    ]
