# Generated by Django 5.2.8 on 2026-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0018_remove_prestamos_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('s', 'Solicitado'), ('p', 'Prestado'), ('m', 'Multa'), ('d', 'Devuelto'), ('r', 'Rechazado')], default='s', max_length=1),
        ),
    ]
