# Generated by Django 5.2.8 on 2026-01-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0021_alter_prestamos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('p', 'Prestado'), ('m', 'Multa'), ('d', 'Devuelto')], default='p', max_length=1),
        ),
    ]
