# Generated by Django 5.2.8 on 2026-01-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0023_solicitudprestamo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudPrestamo',
        ),
    ]
