# Generated by Django 5.2.8 on 2026-01-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0025_solicitudprestamo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudPrestamo',
        ),
    ]
